# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51465f744dad35009b03513f63883056c900956f9fa5552bc91869571cbc7561347c8054615f4d0d28ee35b7694967af4f31c5142c96bee9c7ab764152f79d14

test:
  secret_key_base: 3bae62c0f0745fdb98eba82e15dc457985662154404b6ec527b40c4bae765b5a16a11793e84fcff2764767a1f955693ead0c83b9bccd24de2fd150bc0d8c079f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
